"""WordPress publishing bridge (stub / reference implementation).

Two integration patterns are supported conceptually:

1. Push-as-post: use the WordPress REST API to create/update a post or page
   whose content is the rendered HTML (table + embedded Plotly chart divs).
   Requires an Application Password configured on the WP user
   (WP Admin > Users > Profile > Application Passwords).

2. Static embed: skip this module entirely, drop the files generated by
   `dataforge build` into your theme via the Custom HTML block, an iframe,
   or a PHP `include()` -- no WordPress credentials needed.

This module implements pattern 1. It is intentionally conservative: it will
never delete content, and by default creates a new draft rather than
publishing directly.
"""
from __future__ import annotations

from dataclasses import dataclass

import requests


class WordPressPublishError(Exception):
    pass


@dataclass
class WordPressConfig:
    base_url: str  # e.g. "https://example.com"
    username: str
    app_password: str  # generated in WP Admin > Users > Application Passwords

    @property
    def api_root(self) -> str:
        return self.base_url.rstrip("/") + "/wp-json/wp/v2"


def push_html_as_post(
    config: WordPressConfig,
    *,
    title: str,
    html_content: str,
    status: str = "draft",
    post_type: str = "posts",
) -> dict:
    """Create a new WordPress post/page with the given HTML as its content.

    `status` should be one of: draft, pending, publish. Defaults to draft
    so nothing goes live without a human reviewing it in wp-admin first.
    """
    url = f"{config.api_root}/{post_type}"
    payload = {"title": title, "content": html_content, "status": status}

    resp = requests.post(
        url,
        json=payload,
        auth=(config.username, config.app_password),
        timeout=30,
    )
    if resp.status_code >= 400:
        raise WordPressPublishError(
            f"WordPress API error {resp.status_code}: {resp.text[:500]}"
        )
    return resp.json()
